### ISSUE TITLE
 ModuleNotFoundError: No module named'cuhnsw.cuhnsw_bind' is prompted after installation ubuntu18.04

### ISSUE THREAD

**Issue by dacongzhifu** [js1010/cuhnsw#14]
I want to try the effect and continue to develop on the existing basis, but found that “ModuleNotFoundError: No module named'cuhnsw.cuhnsw_bind' is prompted after installation”，What's the reason for this，thanks！
Below is the relevant log（Username desensitization）
```
(base) xxxxxxx@ubuntu7:~/project/cuhnsw$ python setup.py install
running install
running bdist_egg
running egg_info
writing cuhnsw.egg-info/PKG-INFO
writing dependency_links to cuhnsw.egg-info/dependency_links.txt
writing entry points to cuhnsw.egg-info/entry_points.txt
writing requirements to cuhnsw.egg-info/requires.txt
writing top-level names to cuhnsw.egg-info/top_level.txt
reading manifest file 'cuhnsw.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'cuhnsw.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
copying cuhnsw/version.py -> build/lib.linux-x86_64-3.8/cuhnsw
running build_ext
cuhnsw.cuhnsw_bind
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/pyhnsw.py -> build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/config_pb2.py -> build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/cuhnsw_bind.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/aux.py -> build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/version.py -> build/bdist.linux-x86_64/egg/cuhnsw
copying build/lib.linux-x86_64-3.8/cuhnsw/__init__.py -> build/bdist.linux-x86_64/egg/cuhnsw
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/pyhnsw.py to pyhnsw.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/config_pb2.py to config_pb2.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/aux.py to aux.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/version.py to version.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/__init__.py to __init__.cpython-38.pyc
creating stub loader for cuhnsw/cuhnsw_bind.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/cuhnsw/cuhnsw_bind.py to cuhnsw_bind.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying cuhnsw.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
cuhnsw.__pycache__.aux.cpython-38: module references __file__
cuhnsw.__pycache__.cuhnsw_bind.cpython-38: module references __file__
creating 'dist/cuhnsw-0.0.5-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing cuhnsw-0.0.5-py3.8-linux-x86_64.egg
removing '/home/xxxxxxx/anaconda3/lib/python3.8/site-packages/cuhnsw-0.0.5-py3.8-linux-x86_64.egg' (and everything under it)
creating /home/xxxxxxx/anaconda3/lib/python3.8/site-packages/cuhnsw-0.0.5-py3.8-linux-x86_64.egg
Extracting cuhnsw-0.0.5-py3.8-linux-x86_64.egg to /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
cuhnsw 0.0.5 is already the active version in easy-install.pth

Installed /home/xxxxxxx/anaconda3/lib/python3.8/site-packages/cuhnsw-0.0.5-py3.8-linux-x86_64.egg
Processing dependencies for cuhnsw==0.0.5
Searching for grpcio-tools==1.27.1
Best match: grpcio-tools 1.27.1
Adding grpcio-tools 1.27.1 to easy-install.pth file

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for protobuf==3.10.0
Best match: protobuf 3.10.0
Adding protobuf 3.10.0 to easy-install.pth file

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for numpy==1.19.2
Best match: numpy 1.19.2
Adding numpy 1.19.2 to easy-install.pth file
Installing f2py script to /home/xxxxxxx/anaconda3/bin
Installing f2py3 script to /home/xxxxxxx/anaconda3/bin
Installing f2py3.8 script to /home/xxxxxxx/anaconda3/bin

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for jsmin==2.2.2
Best match: jsmin 2.2.2
Adding jsmin 2.2.2 to easy-install.pth file

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for setuptools==50.3.1.post20201107
Best match: setuptools 50.3.1.post20201107
Adding setuptools 50.3.1.post20201107 to easy-install.pth file
Installing easy_install script to /home/xxxxxxx/anaconda3/bin

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for grpcio==1.35.0
Best match: grpcio 1.35.0
Adding grpcio 1.35.0 to easy-install.pth file

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Searching for six==1.15.0
Best match: six 1.15.0
Adding six 1.15.0 to easy-install.pth file

Using /home/xxxxxxx/anaconda3/lib/python3.8/site-packages
Finished processing dependencies for cuhnsw==0.0.5
(base) xxxxxxx@poisson-ubuntu7:~/project/cuhnsw$ python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cuhnsw
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxxxxxx/project/cuhnsw/cuhnsw/__init__.py", line 6, in <module>
    from cuhnsw.pyhnsw import CuHNSW
  File "/home/xxxxxxx/project/cuhnsw/cuhnsw/pyhnsw.py", line 15, in <module>
    from cuhnsw.cuhnsw_bind import CuHNSWBind
ModuleNotFoundError: No module named 'cuhnsw.cuhnsw_bind'


```

**Comment by dacongzhifu** [comment]
should use `cp ./build/lib.linux-x86_64-3.8/cuhnsw/cuhnsw_bind.cpython-38-x86_64-linux-gnu.so ./cuhnsw` copy this file to cuhnsw dir

**Comment by js1010** [comment]
I think the problem is that you tried to import cuhnsw in cuhnsw dir. Because python will recognize cuhnsw directory (~/project/cuhnsw/cuhnsw) as a package instead of installed cuhnsw package. Could you try to import it in other directory? For example, cd ~/project/cuhnsw/examples and run python.

**Comment by dacongzhifu** [comment]
This problem can also be solved by "cp ./build/lib.linux-x86_64-3.8/cuhnsw/cuhnsw_bind.cpython-38-x86_64-linux-gnu.so ./cuhnsw ", thanks for the reply.
